### ISSUE TITLE
Integrate Profile Page

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#10]
http://www.coderbounty.com/accounts/profile/

**Comment by seanauriti** [comment]
extend the template / accounts...then move the current /profile/ page there and then remove LOGIN_REDIRECT_URL as it is the default

**Comment by seanauriti** [comment]
Profiles will be public...

**Comment by seanauriti** [comment]
Can you please make the default /profile/ show the profile of the logged in user?

**Comment by shashisp** [comment]
Sure, I have a patch ready, I'll send PR

**Comment by seanauriti** [comment]
Great, looking forward to it!
