### ISSUE TITLE
Create a new way to get a Bounty Alert

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#20]

**Comment by enico** [comment]
is there any documentation on getting started contributing both for the coder bounty project and getting started participating in a bounty?

**Comment by seanauriti** [comment]
@enico there is some info on the Readme.  For getting started on a Bounty, if it is open and you code / close it you will get hte bounty.

**Comment by seanauriti** [comment]
This issue was a bit ambiguous - I think I meant something like #103 - closing this one
