### ISSUE TITLE
Implement edit profile

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#22]

**Comment by shashisp** [comment]
@seanauriti is anybody working on this?

**Comment by seanauriti** [comment]
A couple of tweaks:
- [ ] style this page so it looks centered with the title
- [ ]  allow for the user to edit first / last / email
- [ ] allow for the user to link github if they didn't already
- [ ] payment method is only wepay now.  
- [ ] add text: to receive a payout, please register with wepay and enter your wepay email address. (paypal coming soon)

**Comment by seanauriti** [comment]
- [ ] if possible, use allauth to link the github profile, have a button "connect github"
- [ ] when saving, add a message "profile saved" and bring them back to this page.
