### ISSUE TITLE
Design Login Page

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#33]
There are other pages in accounts folder that need this styling - I have applied a first wrapper to the login.  It still needs a bit of design to fit with the layout and style of the site.  additionally the social network links can be replaced with icons - if needed you can use the design from gDrive or if the HTML is straightforward then use that.  This is a screenshot of the most recent look: 

![image](https://cloud.githubusercontent.com/assets/7475382/11199760/a36e18dc-8c9e-11e5-901b-0fcc4c377a42.png)

In terms of the bounty.  We can send it through Wepay, Upwork or Paypal once completed.

**Comment by pedromagnus** [comment]
Hi @seanauriti , maybe you could fill description? it would be using mockups in gDrive, right? What is required? Mockup? HTML+CSS or only a JPG/PSD?
Also, I'm new on this "bounty" stuff, how's it claimed after work is done? Thanks.

**Comment by seanauriti** [comment]
@pedromagnus thanks for asking, I've updated the description.

**Comment by seanauriti** [comment]
@pedromagnus here are the remaining tasks for this:
![image](https://cloud.githubusercontent.com/assets/7475382/11415037/3057df70-93cb-11e5-97c8-03950af8e881.png)

**Comment by pedromagnus** [comment]
Hey Sean, I looked up in the gdrive and didn't find design for this page.
Do you already have custom assets for login buttons or should I look for them?
PS: what about an IRC channel ? ( #coderbounty is available as I'm the only one there :P )

**Comment by seanauriti** [comment]
Thanks @pedromagnus we are chatting in slack  https://coderbounty-slackin.herokuapp.com/

**Comment by seanauriti** [comment]
@pedromagnus Slack also has an irc server - coderbounty.irc.slack.com
what server are you on?
