### ISSUE TITLE
Implement "take" functionality

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#47]
- [x] allow the user to take an issue (create a Taker model)
- [x] the user shows up on the issue and the issue is in the "taken" state (with a nice icon)
- [x] there is a 24 hour countdown showing the users name in the take section with a bomb icon showing the fuze burning
- [x] if the user does not close the issue within 24 hours, there is an explosion next to their name with a bullet hole (http://pngimg.com/upload/small/bullet_hole_PNG6063.png)  and the issue goes back to the open state / (remove the take icon)

---feedback from recent pull request
- [x] 1. change the style of the header back to the color it was
- [x] 2. remove the middle section of time time debug information
- [x] 3. fix the icon to be the user's icon, not an example
- [x] 4. add the time to the takers section
- [x] hide the "take this bounty" button below - also make sure that works for the take feature
- [x] 5. add "psytek has taken this issue and has this much time to submit a solution:"
- [x] 6. when the issue is in the "taken" state, show an input field and "Submit Solution" button
- [x] 7. change the status on the Issue object to "taken" 
- [x] 8. Make sure the data is saved, and when the page refreshes, if the time is not done, show the take section
- [x] 9 make the big icon the userprofile.large_avatar image of the user who is currently taking it
![image](https://cloud.githubusercontent.com/assets/7475382/11414998/af11b2ba-93ca-11e5-8cde-76cef971943b.png)

**Comment by seanauriti** [comment]
http://www.coderbounty.com/issue/26/

**Comment by seanauriti** [comment]
@atuljain thank you for the update, I merged it in and there are a few more things to finish up, please see the comments above.  Looks good so far, excited to have it finished.

**Comment by atuljain** [comment]
thanks for feedback , i will take a look into this and let you know , i will do it

**Comment by atuljain** [comment]
1. change the style of the header back to the color it was

can you please explain me where header is changing , i can't see header changes in my fork

**Comment by atuljain** [comment]
2. remove time debug is done
3. fixed user's icon
4. time added to takers section 
5.  hide the "take this bounty" button below - also make sure that works for the take feature DONE
7. change the status on the Issue object to "taken" Done
 

please explain me 6

**Comment by seanauriti** [comment]
for 6 - when the issue is in the "taken" state, show an input field and "Submit Solution" button - this will be an input field that appears as well for users to submit a pull request as the solution.

for 1 - the header is now green, it used to be red.  It is the same color as the countdown clock so I think that CSS changed it.
