### ISSUE TITLE
Fix remaining page layout for iPad 

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#55]
Homepage and /list is good.  
Can you please also fix:

www.coderbounty.com/post
www.coderbounty.com/issue/1
www.coderbounty.com/help
www.coderbounty.com/about
www.coderbounty.com/terms
http://www.coderbounty.com/profile/shashisp/
http://www.coderbounty.com/accounts/login/

**Comment by serglopatin** [comment]
seems they look fine already (because footer and header are fixed, so content automatically adjusted)... I will just add the same css class, so all pages will have identical layout.

**Comment by seanauriti** [comment]
Ok, here is a screenshot for reference. 
![image](https://cloud.githubusercontent.com/assets/7475382/11169112/7af035b2-8b7b-11e5-8e28-40e1f26a9ffc.png)
