### ISSUE TITLE
Implement recent activity using django-activity

### ISSUE THREAD

**Issue by seanauriti** [seanauriti/coderbounty#6]
https://github.com/justquick/django-activity-stream

**Comment by seanauriti** [comment]
The first activity we track can be 
- [ ] user signup

**Comment by shashisp** [comment]
@seanauriti which all other activities need to be recorded?

**Comment by seanauriti** [comment]
- [ ] add a bounty / new bounty
- [ ] bounty increase
- [ ] bounty won
- [ ] someone took the bounty
- [ ]  bounty re-opened

**Comment by seanauriti** [comment]
Can you please integrate the date - 
![image](https://cloud.githubusercontent.com/assets/7475382/10684902/b1cfeb3a-7920-11e5-9c51-42439d9debcb.png)
