### ISSUE TITLE
 Github signup server error

### ISSUE THREAD

**Issue by akarambir** [seanauriti/coderbounty#79]
Hey, I was trying to signup using Github and got the server error when github sent me back. Is github signup being still worked on?

PS: Got to know from your Upwork post. Great idea :+1:

**Comment by seanauriti** [comment]
Thanks for checking it out!  We had recently upgraded to Django 1.8 and forgot to run the migrations:  Ran them and it is working now:

https://groups.google.com/forum/#!topic/python-social-auth/S3fxcFyL7fk

**Comment by akarambir** [comment]
Nice. I would suggest having migration in post deploy script/hooks. So that you don't have to run migrations manually everytime(assuming code in master is always deployable, as it should be).

**Comment by seanauriti** [comment]
Good idea! Will do. Can you see if the signup is working now?
