### ISSUE TITLE
Remove sensitive info in `settings.py` from git commit history

### ISSUE THREAD

**Issue by mikeumus** [seanauriti/coderbounty#85]
In my `mikeDev` branch I've already removed all the sensitive info in `settings.py` but now just need to BFG is out of the history with this:
- https://help.github.com/articles/remove-sensitive-data/

**Comment by mikeumus** [comment]
This is what I was attempting to do: 
- http://stackoverflow.com/a/1984006/1762493

I'm sure there is a better practice than just keeping the keys in there unless they're "sandbox" keys which I don't think they are.

**Comment by seanauriti** [comment]
The wepay key is a sandbox, I can change the rollbar and secret keys through the variables.  A confit file in this case can be a startup.sh or similar that sets the variables, I am avoiding that extra step by putting in usable sandbox values.

**Comment by mikeumus** [comment]
Alright that's fine, as far as it'll work we'll do it. This is one way we can do sensitive info and we can use BFG to rid the Rollbar secrets if we want/should.
